name: BuildAndPushImageOnHarborAndUpdateArgoCDConfig

on:
  push:
    branches: [ "main" ]
env: 
  REGISTRY: harbor.kube.karsoehome.dk
  REPOSITORY: https://github.com/jennermand/picluster
  PROJECT: guids
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - uses: actions/checkout@v3
    - name: BuildAndPushImageOnHarbor
      run: |
        docker build ./ -t ${{ env.REGISTRY }}/karsoekube/arm-guids:${{ github.run_number }}
        docker push ${{ env.REGISTRY }}/karsoekube/arm-guids:${{ github.run_number }}

    - name: Clone Repository
      run: |
        git clone ${{ env.REPOSITORY }}
    # - name: Install yq
    #   run: |
    #     sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    #     sudo chmod a+x /usr/local/bin/yq
    # - name: Update YAML File
    #   run: |
    #     yq -i '.spec.template.spec.containers[0].image = "harbor.example.com/chaturmail/chaturmail-backend:${{ github.run_number }}"' 'argocd-configs/chaturmail-pod.yaml'
    - name: UpdateRefile
      run: |
        echo "${{ github.run_number }}"> ./apps/${{ env.PROJECT }}/${{ GITHUB_BASE_REF }}.imageref.txt
    - name: Push to Repo
      run: |
        git config --global user.name "${{secrets.USERNAME_GITHUB}}"
        git config --global user.email "${{secrets.EMAIL_GITHUB}}"
        cd argocd-test-configs
        git add .
        git commit -m "Updated by GitHub Actions"
        git push <argocd-config-repo-url> --all
